//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System.Linq;
using System.Web.Security;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Web.UI.WebControls;
using System.Xml.Linq;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web;
using System.Configuration;
using System;
using System.Text;
using System.Web.Profile;
using System.Web.Caching;
using System.Collections;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.WebControls.Expressions;
using System.Collections.Specialized;
using System.Web.SessionState;
using System.Web.DynamicData;

public class site_master : global::System.Web.UI.MasterPage {
protected global::System.Web.UI.WebControls.Button signOut;
protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.Profile.DefaultProfile Profile {
get {
return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
}
}
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
}
}
private string Bind(string expression, string format) {
return "";
}
private string Bind(string expression) {
return "";
}
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
private void @__Render__control5(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
object @__o;

#line 1 "C:\Users\Ridon\AppData\Local\Temp\2C2D4937C91F53D3C37EFE2791A50296B861\2\WebApplication1\Site.Master"
@__o =  Page.Title ;

#line default
#line hidden
}
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
private void @__Render__control6(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
object @__o;

#line 2 "C:\Users\Ridon\AppData\Local\Temp\2C2D4937C91F53D3C37EFE2791A50296B861\2\WebApplication1\Site.Master"
@__o =  Scripts.Render("~/bundles/modernizr") ;

#line default
#line hidden
}
}
}
